name: Enforce PR Source Branch to master branch

on:
  pull_request:
    branches:
      - master

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          echo "Base branch: ${{ github.base_ref }}"
          echo "Head branch: ${{ github.head_ref }}"

          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "Only PRs from 'develop' are allowed into 'master'"
            exit 1
          fi